# Generated by Django 2.2 on 2021-07-03 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='competence',
            new_name='lastname',
        ),
    ]
