# Generated by Django 2.2 on 2021-07-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210703_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='lastname',
            field=models.CharField(max_length=200),
        ),
    ]
